dist: xenial
sudo: true
language: cpp
compiler: gcc

cache:
    - apt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - gcc-7
    coverity_scan:
        project:
            name: "leozz37/texugo"
            description: "Texugo is a simple message switch based on RabbitMQ and modern C++"
        notification_email: leonardoaugusto287@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler $COMPILER --template; cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$COMPILER"
        build_command: "cmake --build build"
        branch_pattern: coverity_scan
    env:
        - COMPILER=g++-7
        - IS_COVERAGE_BUILD=1

install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
    - chmod +x ci/*
    - ci/install-dependencies.sh
    - pip install --user cpp-coveralls
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.3-Linux-x86_64.tar.gz
    - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.17.3-Linux-x86_64 cmake-install
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    - cd ${TRAVIS_BUILD_DIR}
    - cmake --version

script:
    - ci/travis-script.sh

after_success:
    - coveralls -e examples -e tests --gcov-options '\-lp'

notifications:
    email: false