dist: trusty
sudo: true
language: cpp
compiler: gcc

cache:
    - apt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - gcc-9
    coverity_scan:
        project:
            name: "leozz37/texugo"
            description: "Texugo is a simple message switch based on RabbitMQ and modern C++"
        notification_email: leonardoaugusto287@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler $COMPILER --template; cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$COMPILER"
        build_command: "cmake --build build"
        branch_pattern: coverity_scan
    env:
        - COMPILER=g++-9
        - IS_COVERAGE_BUILD=1

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
    - chmod +x scripts/*
    - scripts/travis-before-install.sh

script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 --coverage ..
    - make -j2

after_success:
    - coveralls -e examples -e tests --gcov-options '\-lp'

notifications:
    email: false