dist: trusty
sudo: false
language: cpp

matrix:
    include:
        - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-7
                    - gcc-7
            env:
                - COMPILER=g++-7

script:
    - CXX=/usr/g++5 CC=/usr/bin/gcc-5 cmake .
    - cmake --build . -- -j2