dist: xenial
sudo: true
language: cpp
compiler: gcc

cache:
    - apt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - gcc-9
    coverity_scan:
        project:
            name: "leozz37/texugo"
            description: "Texugo is a simple message switch based on RabbitMQ and modern C++"
        notification_email: leonardoaugusto287@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler $COMPILER --template; cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$COMPILER"
        build_command: "cmake --build build"
        branch_pattern: coverity_scan
    env:
        - COMPILER=g++-9
        - IS_COVERAGE_BUILD=1

before_install:
    - chmod +x ci/*
    - ci/install-dependencies.sh
    - pip install --user cpp-coveralls

script:
    - ci/travis-script.sh

after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
    email: false