version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

inti:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cd ./docker
  - docker build -t texugo .
  
only_commits:
  files:
    - include/
    - resources/
    - src/
    - tests/
    - appveyor.yml
    -CMakeLists.txt